apiVersion: v1
kind: ConfigMap
metadata:
  name: ghreposscorer-config
  namespace: alns-rcpharm-ghrepos-scorer
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: "prod"
  QUARKUS_PROFILE: "prod"
