quarkus.http.port=8081

# GitHub REST Client configuration
quarkus.rest-client."github-api".url=https://api.github.com

# Cache configuration
quarkus.cache.caffeine."github-repositories".expire-after-write=10m

# OpenAPI and Swagger UI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
