# Disable Quarkus Startup Banner for CLI utility
quarkus.banner.enabled=false

# Disable background Quarkus Scheduler during CLI execution
quarkus.scheduler.enabled=false

# Custom output executable name
quarkus.package.output-name=ghreposscorer-util-cli

# Use random free HTTP port for CLI utility
quarkus.http.port=0
